'Event constants
Global Const comEvSEND = 1
Global Const comEvRECEIVE = 2
Global Const comEvCTS = 3
Global Const comEvDSR = 4
Global Const comEvCD = 5
Global Const comEvRING = 6
Global Const comEvEOF = 7

'Error code constants
Global Const comBREAK = 1001
Global Const comCTSTO = 1002
Global Const comDSRTO = 1003
Global Const comFRAME = 1004
Global Const comOVERRUN = 1006
Global Const comCDTO = 1007
Global Const comRXOVER = 1008
Global Const comRXPARITY = 1009
Global Const comTXFULL = 1010
Global Const MSCOMM_HANDSHAKE_NONE = 0
Global Const MSCOMM_HANDSHAKE_RTS = 2

Global cPrograma As String
Global cInstancia As String
Global lModificado As Integer
Global cDirectorio_Programa As String
Global cProfile As String

'File Open/Save Dialog Flags
Global Const OFN_READONLY = &H1&
Global Const OFN_OVERWRITEPROMPT = &H2&
Global Const OFN_HIDEREADONLY = &H4&
Global Const OFN_NOCHANGEDIR = &H8&
Global Const OFN_SHOWHELP = &H10&
Global Const OFN_NOVALIDATE = &H100&
Global Const OFN_ALLOWMULTISELECT = &H200&
Global Const OFN_EXTENSIONDIFFERENT = &H400&
Global Const OFN_PATHMUSTEXIST = &H800&
Global Const OFN_FILEMUSTEXIST = &H1000&
Global Const OFN_CREATEPROMPT = &H2000&
Global Const OFN_SHAREAWARE = &H4000&
Global Const OFN_NOREADONLYRETURN = &H8000&

