
'Event constants
Global Const comEvSEND = 1
Global Const comEvRECEIVE = 2
Global Const comEvCTS = 3
Global Const comEvDSR = 4
Global Const comEvCD = 5
Global Const comEvRING = 6
Global Const comEvEOF = 7

'Error code constants
Global Const comBREAK = 1001
Global Const comCTSTO = 1002
Global Const comDSRTO = 1003
Global Const comFRAME = 1004
Global Const comOVERRUN = 1006
Global Const comCDTO = 1007
Global Const comRXOVER = 1008
Global Const comRXPARITY = 1009
Global Const comTXFULL = 1010
Global Const MSCOMM_HANDSHAKE_NONE = 0
Global Const MSCOMM_HANDSHAKE_RTS = 2
Global cInstancia As String
Global lModificado As Integer

